"""Compiles src/shaders/hwrt.hlsl to DXIL and writes src/shaders/hwrt_shader.inl.

The DXIL blobs are checked in, so building Modeler3D does not need a shader
compiler. Run this after editing hwrt.hlsl. It needs dxc.exe from the Windows
10/11 SDK (it also signs the DXIL through the SDK's dxil.dll), e.g.
    C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x64/dxc.exe
"""
import glob
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "shaders", "hwrt.hlsl")
OUT = os.path.join(ROOT, "src", "shaders", "hwrt_shader.inl")


def find_dxc():
    if len(sys.argv) > 1:
        return sys.argv[1]
    hits = sorted(glob.glob(r"C:/Program Files (x86)/Windows Kits/10/bin/10.*/x64/dxc.exe"))
    if not hits:
        sys.exit("dxc.exe not found: pass its path as the first argument")
    return hits[-1]


def compile_entry(dxc, entry):
    out = os.path.join(tempfile.gettempdir(), "hwrt_%s.dxil" % entry)
    cmd = [dxc, "-nologo", "-T", "cs_6_5", "-E", entry, "-O3", "-HV", "2021", SRC, "-Fo", out]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("dxc failed for %s:\n%s%s" % (entry, r.stdout, r.stderr))
    with open(out, "rb") as f:
        return f.read()


def as_array(name, data):
    lines = ["static const unsigned char %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 20):
        lines.append("    " + ", ".join(str(b) for b in data[i : i + 20]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    dxc = find_dxc()
    trace = compile_entry(dxc, "trace")
    resolve = compile_entry(dxc, "resolve")
    with open(OUT, "w") as f:
        f.write("// Generated by tools/compile_hwrt_shader.py from hwrt.hlsl - do not edit.\n")
        f.write(as_array("kHwrtTraceDXIL", trace) + "\n")
        f.write(as_array("kHwrtResolveDXIL", resolve) + "\n")
    print("wrote %s (trace %d bytes, resolve %d bytes)" % (OUT, len(trace), len(resolve)))


if __name__ == "__main__":
    main()
